fragment UserInfo on User {
  id
  email
  firstName
  lastName
  fullName
  totalPosts
}

fragment UserToken on UserTokenResponse {
  user {
    email
    fullName
  }
  accessToken
}

fragment PostInfo on Post {
  id
  createdAt
  updatedAt
  title
  text
  author {
    id
    fullName
  }
}