fragment UserInfo on User {
  id
  email
  firstName
  lastName
  fullName
  totalPosts
}

fragment UserPosts on User {
  posts {
    id
    createdAt
    updatedAt
    title
    text
    author {
      id
      fullName
    }
  }
}

fragment UserToken on UserTokenResponse {
  user {
    email
    fullName
  }
  accessToken
}

fragment PostInfo on Post {
  id
  createdAt
  updatedAt
  title
  text
  author {
    id
    fullName
  }
}