#import "./fragments.gql"

mutation CreateOneUser($data: UserCreateInput!) {
  createOneUser(data: $data) {
    ...UserInfo
  }
}

mutation CreateOnePost($data: PostCreateInput!) {
  createOnePost(data: $data) {
    ...PostInfo
  }
}

mutation UpdateOnePost($data: PostUpdateInput!, $where: PostWhereUniqueInput!) {
  updateOnePost(data: $data, where: $where) {
    id
  }
}

mutation DeleteOnePost($where: PostWhereUniqueInput!) {
  deleteOnePost(where: $where) {
    id
  }
}

mutation SignIn($data: SignInInput!) {
  signIn(data: $data) {
    ...UserToken
  }
}

mutation SignUp($data: SignUpInput!) {
  signUp(data: $data) {
    ...UserToken
  }
}
