#import "./fragments.gql"

mutation CreateOneUser($data: UserCreateInput!) {
  createOneUser(data: $data) {
    ...UserInfo
  }
}

mutation CreateOnePost($data: PostCreateInput!) {
  createOnePost(data: $data) {
    ...PostInfo
  }
}

mutation DeleteOnePost($data: PostWhereUniqueInput!) {
  deleteOnePost(where: $data) {
    id
  }
}

mutation SignIn($data: SignInInput!) {
  signIn(data: $data) {
    ...UserToken
  }
}

mutation SignUp($data: SignUpInput!) {
  signUp(data: $data) {
    ...UserToken
  }
}
