#import "./fragments.gql"

mutation CreateOneUser($data: UserCreateInput!) {
  createOneUser(data: $data) {
    ...UserInfo
  }
}

mutation SignIn($data: SignInInput!) {
  signIn(data: $data) {
    ...UserToken
  }
}

mutation SignUp($data: SignUpInput!) {
  signUp(data: $data) {
    ...UserToken
  }
}
