#import "./fragments.gql"

query GetUsers {
  users {
    ...UserInfo
  }
}

query GetPostsByUser($authorId: String!) {
  postsByUser(data: { authorId: $authorId }) {
    ...PostInfo
  }
}

query GetPosts {
  posts {
    ...PostInfo
  }
}
