#import "./fragments.gql"

query GetUsers {
  users {
    ...UserInfo
  }
}

query GetUserPosts($userId: String!) {
  user(where: { id: $userId}) {
    ...UserPosts
  }
}

query GetPosts {
  posts {
    ...PostInfo
  }
}
